### ISSUE TITLE
White on white text in the newsletter fields

### ISSUE THREAD

**Issue by TantienHime** [WordCamp-Canada/WordCamp-Canada-Website#2]
From the contact form:

Michael Milette| /contact | 2024/02/11 | NameMichael Milette Email: michael.milette@tngconsulting.ca

When I try to type into the field to sign up for the newsletter, the text is white on white. I cannot see what I am typing unless I highlight everything in the field. I therefore recommend fixing this.

Browser: Google Chrome (latest version) for Windows

Best regards, Michael
Source: https://canada.wordcamp.org/2024/contact/

**Comment by kierahowe** [comment]
I fixed this a few days ago
